package microtome.test {

// GENERATED IMPORTS START
import microtome.Tome;
// GENERATED IMPORTS END

// GENERATED CLASS_INTRO START
public interface ListTome extends Tome
{
// GENERATED CLASS_INTRO END

// GENERATED CLASS_BODY START
    function get kids () :Array;
// GENERATED CLASS_BODY END

// GENERATED CLASS_OUTRO START
}
}
// GENERATED CLASS_OUTRO END
